# Generated by Django 5.2.5 on 2025-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="content_type",
            field=models.CharField(
                choices=[("text", "Texte"), ("link", "Lien"), ("image", "Image")],
                default="text",
                max_length=10,
                verbose_name="Type de contenu",
            ),
        ),
    ]
