# Generated by Django 5.2.4 on 2025-08-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('theme', models.CharField(choices=[('politique', 'Politique'), ('finance', 'Finance'), ('sport', 'Sport'), ('technologie', 'Technologie'), ('science', 'Science'), ('culture', 'Culture'), ('international', 'International'), ('sante', 'Santé')], max_length=20)),
                ('read_time', models.CharField(default='5 min', max_length=10)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('politique', 'Politique'), ('finance', 'Finance'), ('sport', 'Sport'), ('technologie', 'Technologie'), ('science', 'Science'), ('culture', 'Culture'), ('international', 'International'), ('sante', 'Santé')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('gradient', models.CharField(choices=[('from-blue-500 to-indigo-600', 'Bleu-Indigo'), ('from-green-500 to-emerald-600', 'Vert-Emeraude'), ('from-orange-500 to-red-600', 'Orange-Rouge'), ('from-purple-500 to-violet-600', 'Violet-Pourpre'), ('from-cyan-500 to-blue-600', 'Cyan-Bleu'), ('from-pink-500 to-rose-600', 'Rose-Pink'), ('from-teal-500 to-cyan-600', 'Teal-Cyan'), ('from-red-500 to-pink-600', 'Rouge-Rose')], max_length=50)),
                ('bg_color', models.CharField(default='bg-primary-50', max_length=20)),
                ('text_color', models.CharField(default='text-primary-700', max_length=20)),
                ('icon_name', models.CharField(default='Building2', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
