"""
Django settings for factguard_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT ajouté à sys.path :", str(PROJECT_ROOT))

# Chargement sécurisé des secrets
try:
    from config.secrets import secrets_manager
    USE_KEY_VAULT = True
    print(" Azure Key Vault configuré avec succès")
except ImportError as e:
    USE_KEY_VAULT = False
    print(f" Fallback vers variables d'environnement: {e}")

load_dotenv()


def get_secret(secret_name, env_name=None):
    if USE_KEY_VAULT:
        return secrets_manager.get_secret(secret_name, env_name or secret_name)
    return os.getenv(env_name or secret_name)  


# === RÉCUPÉRATION DES SECRETS ===
SECRET_KEY = get_secret('SECRET-KEY', 'SECRET_KEY')

# Azure OpenAI
AZURE_OPENAI_API_KEY = get_secret('AZURE-OPENAI-API-KEY', 'AZURE_OPENAI_API_KEY')
AZURE_OPENAI_ENDPOINT = get_secret('AZURE-OPENAI-ENDPOINT')        
AZURE_OPENAI_API_VERSION = get_secret('AZURE-OPENAI-API-VERSION')  
AZURE_OPENAI_DEPLOYMENT_NAME = get_secret('AZURE-OPENAI-DEPLOYMENT-NAME')
# Azure Search
AZURE_SEARCH_ENDPOINT = get_secret('AZURE-SEARCH-ENDPOINT', 'AZURE_SEARCH_ENDPOINT')
AZURE_SEARCH_ADMIN_KEY = get_secret('AZURE-SEARCH-ADMIN-KEY', 'AZURE_SEARCH_ADMIN_KEY')
AZURE_SEARCH_INDEX_NAME = get_secret("factguard-articles-index")

# News API
NEWS_API_KEY = get_secret('NEWS-API-KEY', 'NEWS_API_KEY')

# Monitoring
APPLICATIONINSIGHTS_CONNECTION_STRING = get_secret('APPLICATIONINSIGHTS-CONNECTION-STRING', 'APPLICATIONINSIGHTS_CONNECTION_STRING')

# === ALIAS POUR COMPATIBILITÉ ===
AZURE_SEARCH_API_KEY = AZURE_SEARCH_ADMIN_KEY

# === INJECTION DANS OS.ENVIRON POUR LE CODE MÉTIER ===
# (Nécessaire car certains modules utilisent os.getenv directement)
environment_mappings = {
    'AZURE_OPENAI_API_KEY': AZURE_OPENAI_API_KEY,
    'AZURE_OPENAI_ENDPOINT': AZURE_OPENAI_ENDPOINT,
    'AZURE_OPENAI_API_VERSION': AZURE_OPENAI_API_VERSION,
    'AZURE_OPENAI_DEPLOYMENT_NAME': AZURE_OPENAI_DEPLOYMENT_NAME,
    
    'AZURE_SEARCH_API_KEY': AZURE_SEARCH_API_KEY,
    'AZURE_SEARCH_ENDPOINT': AZURE_SEARCH_ENDPOINT,
    'AZURE_SEARCH_ADMIN_KEY': AZURE_SEARCH_ADMIN_KEY,
    'AZURE_SEARCH_INDEX_NAME': AZURE_SEARCH_INDEX_NAME,
    
    'NEWS_API_KEY': NEWS_API_KEY,
    
    'APPLICATIONINSIGHTS_CONNECTION_STRING': APPLICATIONINSIGHTS_CONNECTION_STRING,
}

# Injecter dans os.environ
for key, value in environment_mappings.items():
    if value:
        os.environ[key] = str(value)




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lnf=s!k^-qs#(39)=-+odx0j_tds!dfhm5^h7$anlcidw)leoe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',  
    'dashboard',
    'recommendations',
    'data_pipeline',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'factguard_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'factguard_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirections après login / logout
LOGIN_REDIRECT_URL = "dashboard:analyzer"
LOGOUT_REDIRECT_URL = "home:index"

